### ISSUE TITLE
Error messages when using parallelize=True

### ISSUE THREAD

**Issue by chuaxr** [spencerahill/aospy#210] opened 2017-10-08 23:53 UTC
Using parallelize=True in aospy_main gives the following error messages, although output still seems to be produced normally. I'm not familiar with multiprocessing, and would appreciate a heads-up if there's anything I should be worried about.
> 
> 
> INFO:root:Writing desired gridded outputs to disk.
> INFO:root:	/work/xrc/CRM/WRF/RCE_base_ideal_evap/rqvten_phys_tmean_cond_prcp/rqvten_phys_tmean_cond_prcp.ann.s_av.from_1hr_ts.WRF.RCE_base_ideal_evap.20010720.20010730.nc
> INFO:root:Computing timeseries for 2001-07-20 01:00:00 -- 2001-07-30 00:00:00.
> /nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/variable.py:1143: RuntimeWarning: invalid value encountered in less
>   if not reflexive
> INFO:root:Applying desired time-reduction methods. (Sun Oct  8 19:41:56 2017)
> INFO:root:Writing desired gridded outputs to disk.
> INFO:root:	/work/xrc/CRM/WRF/RCE_heat_tropo_ideal_evap/rqvten_phys_tmean_cond_prcp/rqvten_phys_tmean_cond_prcp.ann.s_av.from_1hr_ts.WRF.RCE_heat_tropo_ideal_evap.20010720.20010730.nc
> distributed.nanny - INFO - Worker closed
> distributed.nanny - INFO - Worker closed
> tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2ba6c93c0268>, <tornado.concurrent.Future object at 0x2ba6c93a0470>)
> Traceback (most recent call last):
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>     ret = callback()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
>     future.result()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
>     yielded = self.gen.send(value)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 216, in _stop_worker
>     self.workers.remove(w)
> ValueError: list.remove(x): x not in list
> tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2ba6c912b8c8>, <tornado.concurrent.Future object at 0x2ba6c9125978>)
> Traceback (most recent call last):
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>     ret = callback()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
>     future.result()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
>     yielded = self.gen.send(value)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 216, in _stop_worker
>     self.workers.remove(w)
> ValueError: list.remove(x): x not in list
> (py361) ~/WRF/aospy_code$ /nbhome/xrc/anaconda2/envs/py361/lib/python3.6/multiprocessing/semaphore_tracker.py:129: UserWarning: semaphore_tracker: There appear to be 5 leaked semaphores to clean up at shutdown
>   len(cache))
>

**Comment by spencerkclark** [comment] 2017-10-09 01:20
@chuaxr thanks for the report.  Two quick questions to aid in diagnosing the issue:
1. What version of `distributed` do you have installed?  E.g. in an `ipython` shell:
```
In [1]: import distributed

In [2]: distributed.__version__
Out[2]: '1.17.1'
```
2. Does this happen deterministically?  In other words do you get this same error in the same place every time you run the main script?

**Comment by chuaxr** [comment] 2017-10-09 01:32
1. I was on 1.16.3. The error messages disappeared after I upgraded to the latest version on conda-forge (1.19.2), if that helps.

2. This is the error log from the other time I tried it, which appears to be the same in essentials:

> INFO:root:	/work/xrc/CRM/WRF/RCE_heat_tropo_ideal_evap/rqvten_advh_tmean_cond_prcp/rqvten_advh_tmean_cond_prcp.ann.s_av.from_1hr_ts.WRF.RCE_heat_tropo_ideal_evap.20010720.20010730.nc
> distributed.nanny - INFO - Worker closed
> distributed.nanny - INFO - Worker closed
> distributed.nanny - INFO - Worker closed
> distributed.nanny - INFO - Worker closed
> distributed.nanny - INFO - Worker closed
> distributed.nanny - INFO - Worker closed
> distributed.nanny - INFO - Worker closed
> distributed.nanny - INFO - Worker closed
> tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2b92f5db4598>, <tornado.concurrent.Future object at 0x2b92f5db1c18>)
> Traceback (most recent call last):
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>     ret = callback()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
>     future.result()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
>     yielded = self.gen.send(value)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 216, in _stop_worker
>     self.workers.remove(w)
> ValueError: list.remove(x): x not in list
> tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2b93000fb378>, <tornado.concurrent.Future object at 0x2b93000f3080>)
> Traceback (most recent call last):
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>     ret = callback()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
>     future.result()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
>     yielded = self.gen.send(value)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 216, in _stop_worker
>     self.workers.remove(w)
> ValueError: list.remove(x): x not in list
> tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2b93000f1e18>, <tornado.concurrent.Future object at 0x2b93000eb6d8>)
> Traceback (most recent call last):
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>     ret = callback()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
>     future.result()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
>     yielded = self.gen.send(value)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 216, in _stop_worker
>     self.workers.remove(w)
> ValueError: list.remove(x): x not in list
> tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2b93000ed950>, <tornado.concurrent.Future object at 0x2b93000ddd30>)
> Traceback (most recent call last):
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>     ret = callback()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
>     future.result()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
>     yielded = self.gen.send(value)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 216, in _stop_worker
>     self.workers.remove(w)
> ValueError: list.remove(x): x not in list
> tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2b93000e8488>, <tornado.concurrent.Future object at 0x2b93000dd3c8>)
> Traceback (most recent call last):
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>     ret = callback()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
>     future.result()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
>     yielded = self.gen.send(value)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 216, in _stop_worker
>     self.workers.remove(w)
> ValueError: list.remove(x): x not in list
> tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2b93000e3f28>, <tornado.concurrent.Future object at 0x2b93000d7be0>)
> Traceback (most recent call last):
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>     ret = callback()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
>     future.result()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
>     yielded = self.gen.send(value)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 216, in _stop_worker
>     self.workers.remove(w)
> ValueError: list.remove(x): x not in list
> tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2b93000dfa60>, <tornado.concurrent.Future object at 0x2b93000d1e48>)
> Traceback (most recent call last):
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>     ret = callback()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
>     future.result()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
>     yielded = self.gen.send(value)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 216, in _stop_worker
>     self.workers.remove(w)
> ValueError: list.remove(x): x not in list
> tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2b93000aba60>, <tornado.concurrent.Future object at 0x2b9300065278>)
> Traceback (most recent call last):
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>     ret = callback()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
>     future.result()
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 4, in raise_exc_info
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
>     yielded = self.gen.send(value)
>   File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 216, in _stop_worker
>     self.workers.remove(w)
> ValueError: list.remove(x): x not in list
> (py361) ~/WRF/aospy_code$ /nbhome/xrc/anaconda2/envs/py361/lib/python3.6/multiprocessing/semaphore_tracker.py:129: UserWarning: semaphore_tracker: There appear to be 10 leaked semaphores to clean up at shutdown
>   len(cache))
>

**Comment by spencerkclark** [comment] 2017-10-09 01:41
@chuaxr nice, so upgrading `distributed` seems to have fixed things!  

@spencerahill it looks like in our `setup.py` file we only require a `distributed` version of greater than `1.16.1`:
https://github.com/spencerahill/aospy/blob/d76f74cf2165594a2376e1e183c78e20ac406c01/setup.py#L35 In light of this issue, do you think we should bump that minimum version up?

**Comment by spencerahill** [comment] 2017-10-09 03:00
@chuaxr thanks for the bug report

>In light of this issue, do you think we should bump that minimum version up?

@spencerkclark it would be nice if we knew the cause of the bug -- as it stands, what would be the new minimum version? 1.17.1, because that's what you're on and you haven't come across this?

From @chuaxr's traceback the place to start looking would be `distributed/deploy/local.py", line 216, in _stop_worker`

**Comment by spencerkclark** [comment] 2017-10-09 10:22
@spencerahill yes `1.17.1` would be the new minimum version; the relevant distributed issue is here https://github.com/dask/distributed/issues/1166 and it was fixed in https://github.com/dask/distributed/commit/0b8ebe0f1ec0680ee78138d99947ea9086a61452, which made it into `1.17.1` (released on June 14th).

**Closed as completed** 2017-10-09 14:35 UTC
